version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Основной порт для клиентов Kafka
      ZOOKEEPER_TICK_TIME: 2000  # Интервал между тиками (внутренний таймер Zookeeper)
    volumes:
      - ./zookeeper-logs:/var/log/zookeeper
    logging:
      driver: "json-file"  # Логирование в JSON-файл
      options:
        max-size: "5m"  # Максимальный размер одного лог-файла
        max-file: "3"   # Хранить до 3 лог-файлов

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1  # Уникальный ID брокера в кластере Kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Адрес Zookeeper внутри Docker-сети
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Как Kafka будет представляться клиентам (важно для подключения извне)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      # Указываем, что используем обычный (не TLS) протокол
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        # Кол-во реплик для служебных топиков (offset'ы и т.д.)
      # 1 — достаточно для одного брокера
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Позволяет автоматически создавать топики при первом использовании
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
      # Ограничение памяти JVM Kafka — важно для слабых VPS
      KAFKA_NUM_NETWORK_THREADS: 2
      # Кол-во потоков для сетевых операций — меньше потоков = меньше нагрузка
      KAFKA_NUM_IO_THREADS: 2
      # Потоки для операций с диском — тоже ограничиваем
      KAFKA_NUM_PARTITIONS: 1
      # Кол-во партиций по умолчанию при создании топика — 1 достаточно для тестов
      KAFKA_JVM_PERFORMANCE_OPTS: ""
    volumes:
      - ./kafka/kafka-logs:/var/log/kafka
      # Выносим логи Kafka на хост-машину, чтобы они сохранялись вне контейнера
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Максимальный размер одного лог-файла
        max-file: "3"    # Хранить до 3 лог-файлов
    depends_on:
      - zookeeper  # Kafka запускается только после Zookeeper — важная зависимость
